stamp_duty:
  en:
    id: "20289328"
    url: "https://mastest.zendesk.com"
    name: Feedback
  cy:
    id: "20281613"
    url: "https://mastest.zendesk.com"
    name: Adborth
affordability:
  en:
    id: "20293976"
    url: "https://mastest.zendesk.com"
    name: Feedback
  cy:
    id: "20283353"
    url: "https://mastest.zendesk.com"
    name: Adborth
repayment:
  en:
    id: "20283343"
    url: "https://mastest.zendesk.com"
    name: Feedback
  cy:
    id: "20291388"
    url: "https://mastest.zendesk.com"
    name: Adborth
