#!/bin/bash -l

set -e

if [ -f /.dockerenv ]; then
    source ~/.bashrc
    rvm use default
fi

export RAILS_ENV=test

mkdir -p spec/dummy/tmp/capybara

exit_code=0

function run {
    declare -a tests_command=("$@")
    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}

function info {
    declare -a info_command=("$@")
    echo ''
    echo "=== Running for informational purposes \`${info_command[*]}\`"
    if ! ${info_command[*]}; then
        echo "== This test has errors and/or warnings. Please review results"
    fi
}

run npm install --quiet
run bundle install
run bundle update brakeman --quiet
run bundle exec bowndler update --allow-root
run bundle exec rspec -f progress
run bundle exec cucumber -f progress
run bundle exec rake app:karma:run_once
run brakeman -q --no-pager --ensure-latest --no-exit-on-warn

if [ -f /.dockerenv ]; then
  run bundle exec danger --dangerfile=jenkins/Dangerfile --verbose
fi

exit "$exit_code"
