#!/bin/bash

set -e

export RAILS_ENV=test
export BUNDLE_WITHOUT=development:build

mkdir -p spec/dummy/tmp/capybara

exit_code=0

function run {
    declare -a tests_command=("$@")

    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}

run npm install
run bundle install
run bundle exec bowndler update --allow-root
#run brakeman -q --no-pager --ensure-latest
run bundle exec rspec
run bundle exec cucumber
run bundle exec rake app:karma:run_once

exit "$exit_code"
